export const SkillsItems = [
  {
    path: "react-native.svg",
    name: "React",
    info: "",
    color: "rgba(0, 216, 255, 0.1)",
  },
  {
    path: "redux.svg",
    name: "Redux",
    info: "",
    color: "rgba(102, 0, 204, 0.1)",
  },
  {
    path: "typescript.svg",
    name: "TypeScript",
    info: "",
    color: "rgba(45, 121, 199, 0.1)",
  },
  {
    path: "c++.svg",
    name: "C++",
    info: "",
    color: "rgba(0, 66, 131, 0.1)",
  },
  {
    path: "python.svg",
    name: "Python",
    info: "",
    color: "rgba(255, 215, 72, 0.1)",
  },
  {
    path: "nodejs.svg",
    name: "Node.js",
    info: "",
    color: "rgba(110, 168, 96, 0.1)",
  },
  {
    path: "angular.png",
    name: "Angular",
    info: "",
    color: "rgba(255, 128, 128, 0.1)",
  },
  {
    path: "mongodb.svg",
    name: "MongoDB",
    info: "",
    color: "rgba(0, 153, 51, 0.1)",
  },
  {
    path: "express.png",
    name: "Express.js",
    info: "",
    color: "rgba(0, 0, 102, 0.1)",
  },
  {
    path: "postgresql.svg",
    name: "PostgreSQL",
    info: "",
    color: "rgba(51, 103, 145, 0.1)",
  },
  {
    path: "graphql.svg",
    name: "GraphQL",
    info: "",
    color: "rgba(229, 53, 171, 0.1)",
  },
  {
    path: "next.png",
    name: "Next.js",
    info: "",
    color: "rgba(102, 102, 153, 0.1)",
  },
  {
    path: "java.png",
    name: "Java",
    info: "",
    color: "rgba(102, 204, 255, 0.1)",
  },
  {
    path: "git.png",
    name: "Git",
    info: "",
    color: "rgba(255, 102, 0, 0.1)",
  },
  {
    path: "figma.svg",
    name: "Figma",
    info: "",
    color: "rgba(162, 89, 255, 0.1)",
  },
  {
    path: "graphql.svg",
    name: "AWS",
    info: "",
    color: "rgba(229, 53, 171, 0.1)",
  },
  {
    path: "next.png",
    name: "Docker",
    info: "",
    color: "rgba(102, 102, 153, 0.1)",
  },
  {
    path: "java.png",
    name: "SQL",
    info: "",
    color: "rgba(102, 204, 255, 0.1)",
  },
];
